### ISSUE TITLE
Trebuie adaugat campul "id_cheltuiala"

### ISSUE THREAD

**Issue by ClaudiuDC21** [AP-MI-2021/lab-567-ClaudiuDC21#1]
Numarul apartamentului nu poate fi neaparat unic. Intr-o asociatie de blocuri, numarul unui apartament se poate repeta. Mai este si cazul in care cheltuielile aceluiasi apartament se repeta, iar in aceste cazuri trebuie inserat un id care sa fie tot timpul unic.

**Comment by ivdorelian** [comment]
Trebuie id_cheltuiala, nu id_apartament.
